<a href="https://colab.research.google.com/github/felipefr/numerical_analysis/blob/main/NumRepres_Ex2_SingleDouble.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

$exp(A) = I + A + \frac{A^2}{2!} + ... + \frac{A^N}{N!}$

In [ ]:
import numpy as np
import math

def exp_series(A, N):
  expA = np.eye(A.shape[0])
  for i in range(1, N+1):
    expA = expA + np.linalg.matrix_power(A, i) / math.factorial(i)

  return expA

In [ ]:
A = np.array([[-49., 24.], [-64., 31.]], dtype = 'float64')

N=80
for i in range(1,N,10):
  print("expA (i=%d) = "%i)
  print(exp_series(A, i))


expA (i=1) = 
[[-48.  24.]
 [-64.  32.]]
expA (i=11) = 
[[-1541251.8193969    770626.09363817]
 [-2055002.91636845  1027501.82606366]]
expA (i=21) = 
[[-1788349.7624379992 894175.0651587208]
 [-2384466.8404232515 1192233.7880910663]]
expA (i=31) = 
[[-17756.309546437667 8878.33871294068]
 [-23675.56990117028 11838.152830026265]]
expA (i=41) = 
[[-8.027068733727347 4.197474088714856]
 [-11.193264231719375 5.964511556986523]]
expA (i=51) = 
[[-0.7360294710276579 0.5519544573650152]
 [-1.471878548119786 1.1038187151867347]]
expA (i=61) = 
[[-0.7357587570773017 0.5518191003898372]
 [-1.4715175961859774 1.1036382392198305]]
expA (i=71) = 
[[-0.7357587556218489 0.5518190996621108]
 [-1.4715175942453735 1.1036382382495284]]


In [ ]:
A = np.array([[-49., 24.], [-64., 31.]], dtype = 'float32')

N=60
for i in range(1,N,10):
  print("expA (i=%d) = "%i)
  print(exp_series(A, i))

expA (i=1) = 
[[-48.  24.]
 [-64.  32.]]
expA (i=11) = 
[[-1541251.32523448   770625.93799115]
 [-2055002.56967185  1027501.82142358]]
expA (i=21) = 
[[-1788345.0575370616 894173.2151528583]
 [-2384459.645723545 1192229.0446993737]]
expA (i=31) = 
[[-inf inf]
 [-inf inf]]
expA (i=41) = 
[[nan nan]
 [nan nan]]
expA (i=51) = 
[[nan nan]
 [nan nan]]


/usr/local/lib/python3.10/dist-packages/numpy/linalg/linalg.py:680: RuntimeWarning: overflow encountered in matmul
  result = z if result is None else fmatmul(result, z)
/usr/local/lib/python3.10/dist-packages/numpy/linalg/linalg.py:677: RuntimeWarning: overflow encountered in matmul
  z = a if z is None else fmatmul(z, z)
<ipython-input-72-85b3c18adcde>:7: RuntimeWarning: invalid value encountered in add
  expA = expA + np.linalg.matrix_power(A, i) / math.factorial(i)
/usr/local/lib/python3.10/dist-packages/numpy/linalg/linalg.py:680: RuntimeWarning: invalid value encountered in matmul
  result = z if result is None else fmatmul(result, z)


Par décomposition aux valeurs propres : $\exp(A) = V \exp(D) V^{-1}$

In [ ]:
A = np.array([[-49., 24.], [-64., 31.]], dtype = 'float32')
D,V = np.linalg.eig(A)
print("V = ", V)
print("D = ", D)
eA = V@np.diag([np.exp(D[0]),np.exp(D[1])])@np.linalg.inv(V)
print("eA = ", eA)

V =  [[-0.6       -0.4472136]
 [-0.8       -0.8944272]]
D =  [-17.  -1.]
eA =  [[-0.73575866  0.5518191 ]
 [-1.4715174   1.1036382 ]]
